-
  branches:
    only:
      - development
      - master

  version: 1502.0.{build}-{branch}

  platform:
    - x86
    - ARM

  configuration:
    - Debug
    - Release


  matrix:
  allow_failures:
    - branch: development